### ISSUE TITLE
Mixup.py doing an invalid mixing

### ISSUE THREAD

**Issue by mayii2001** [yixiangD/AccurateBG#3]
Hi. The basic principle of MixUp is to mix two different data points together, and the specific step should be to select two different data points from the minority class, but the [code](https://github.com/yixiangD/AccurateBG/blob/main/accurate_bg/mixup.py#L44) use the same data array from beginning to end, lacking a random shuffle.

**Comment by yixiangD** [comment]
thanks. we have revisited it and updated it accordingly. it should be good now.
